### ISSUE TITLE
Compilation issue on Ubuntu and Ubuntu WSL on windows

### ISSUE THREAD

**Issue by Evanok** [franshej/CustomMatPlot#2]
Hi,

I am able to compile this library on Windows but not on Ubuntu.

> /home/xxxx/arthur/CustomMatPlot/source/cmp_plot.cpp:201:30: error: no match for ‘operator!=’ (operand types are ‘const Lim_f’ {aka ‘const cmp::Lim<float>’} and ‘cmp::Lim<float>’)
>   201 |   if (new_x_lim && new_x_lim != m_x_lim) {
>       |                    ~~~~~~~~~ ^~ ~~~~~~~
>       |                    |            |
>       |                    Lim<[...]>   Lim<[...]>
> /home/xxxxx/arthur/CustomMatPlot/source/cmp_plot.cpp:201:30: note: candidate: ‘operator!=(int, int)’ <built-in>
>   201 |   if (new_x_lim && new_x_lim != m_x_lim) {
>       |                    ~~~~~~~~~~^~~~~~~~~~
> /home/xxxx/arthur/CustomMatPlot/source/cmp_plot.cpp:201:30: note:   no known conversion for argument 2 from ‘cmp::Lim<float>’ to ‘int’
> /home/xxxx/arthur/CustomMatPlot/source/cmp_plot.cpp:228:28: error: no match for ‘operator!=’ (operand types are ‘cmp::Lim<float>’ and ‘const Lim_f’ {aka ‘const cmp::Lim<float>’})
>   228 |   if (new_y_lim && m_y_lim != new_y_lim) {
>       |                    ~~~~~~~ ^~ ~~~~~~~~~
>       |                    |          |
>       |                    Lim<[...]> Lim<[...]>
> 

I have to put this change  to compile it properly:

```
diff --git a/include/include/cmp_datamodels.h b/include/include/cmp_datamodels.h
index 43604a0..850a862 100644
--- a/include/include/cmp_datamodels.h
+++ b/include/include/cmp_datamodels.h
@@ -121,6 +121,10 @@ struct Lim {
     return min == rhs.min && max == rhs.max;
   }

+  bool operator!=(const Lim<ValueType>& rhs) const noexcept {
+    return min != rhs.min || max != rhs.max;
+  }
+
   constexpr explicit operator bool() const noexcept {
     constexpr auto zero = static_cast<ValueType>(0);
```

**Comment by franshej** [comment]
Thank you very much for reporting this. Fixed in f8634e4c223d317fc35d2ff40c432a3d3b474bc4
