### ISSUE TITLE
remove warning in cmp_lookandfeel.cpp

### ISSUE THREAD

**Issue by JoergBitzer** [franshej/CustomMatPlot#3]
line 539
 switch (grid_line.direction) {
g.setColour(findColour(Plot::grid_colour));
case ....

g,setColour is never executed, because of the case statements
the correct solution ( IMHO) is to exchange the two lines

g.setColour(findColour(Plot::grid_colour));
 switch (grid_line.direction) {

Overall: Great Work.

**Comment by franshej** [comment]
Thanks!
